#!/usr/bin/env python3
import argparse
from pathlib import Path

def read_gro(path):
    lines = Path(path).read_text().splitlines()
    title = lines[0]
    n = int(lines[1].strip())
    atoms = lines[2:2+n]
    box = lines[2+n]
    return title, atoms, box

def renumber_gro_atom_line(line, new_index):
    # GRO fixed-ish format: residue nr cols 1-5, res name 6-10, atom name 11-15, atom nr 16-20
    return f"{line[:15]}{new_index % 100000:5d}{line[20:]}"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--protein-gro", required=True)
    ap.add_argument("--ligand-gro", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    _, patoms, pbox = read_gro(args.protein_gro)
    _, latoms, _ = read_gro(args.ligand_gro)

    all_atoms = patoms + latoms
    renumbered = [renumber_gro_atom_line(line, i+1) for i, line in enumerate(all_atoms)]

    out = ["Protein-ligand complex generated by pipeline", f"{len(renumbered):5d}"]
    out.extend(renumbered)
    out.append(pbox)
    Path(args.output).write_text("\n".join(out) + "\n")
    print(f"Wrote {args.output} with {len(renumbered)} atoms")

if __name__ == "__main__":
    main()
